[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
home=['<Super>e']

[custom-keybindings/custom0]
binding='<Control>space'
command='vicinae toggle'
name='Vicinae'
